apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      # - "https://download.elastic.co/downloads/eck/2.1.0/crds.yaml"
      - "./infra/k8s/*"
      - "./infra/k8s-dev/*"
build:
  local:
    push: false
  artifacts:
    - image: hydrophonix/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: "." 
            src: "src/**/*.ts" 

    - image: hydrophonix/feed
      context: feed
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: "." 
            src: "src/**/*.ts" 

    - image: hydrophonix/posts
      context: posts
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: "." 
            src: "src/**/*.ts" 

    - image: hydrophonix/comments
      context: comments
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: "." 
            src: "src/**/*.ts" 

    - image: hydrophonix/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: "." 
            src: "src/**/*.ts"
          - dest: "." 
            src: "src/**/*.tsx"