apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-srv
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: 'true'
  labels:
    name: ingress-srv
spec:
  rules:
  - host: microservices.dev
    http:
      paths:
      - path: "/api/(auth|users)/?(.*)"
        pathType: Prefix
        backend:
          service:
            name: auth-srv
            port: 
              number: 3000

      - path: "/api/feed/?(.*)"
        pathType: Prefix
        backend:
          service:
            name: feed-srv
            port: 
              number: 3000

      - path: "/api/posts/?(.*)"
        pathType: Prefix
        backend:
          service:
            name: posts-srv
            port: 
              number: 3000

      - path: "/?(.*)"
        pathType: Prefix
        backend:
          service:
            name: client-srv
            port: 
              number: 3000
